/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
'use strict';

systemDictionary = {
    'rollershutter-arduino adapter settings': {
        'en': 'Adapter settings for rollershutter-arduino',
        'de': 'Adaptereinstellungen für rollershutter-arduino',
        'ru': 'Настройки адаптера для rollershutter-arduino',
        'pt': 'Configurações do adaptador para rollershutter-arduino',
        'nl': 'Adapterinstellingen voor rollershutter-arduino',
        'fr': "Paramètres d'adaptateur pour rollershutter-arduino",
        'it': "Impostazioni dell'adattatore per rollershutter-arduino",
        'es': 'Ajustes del adaptador para rollershutter-arduino',
        'pl': 'Ustawienia adaptera dla rollershutter-arduino',
        'uk': 'Налаштування адаптера для rollershutter-arduino',
        'zh-cn': 'rollershutter-arduino的适配器设置'
    },
    'serial_connection_settings': {
        'en': 'Serial Connection Settings',
        'de': 'Serielle Verbindungseinstellungen',
        'ru': 'Настройки последовательного соединения',
        'pt': 'Configurações de Conexão Serial',
        'nl': 'Seriële Verbindingsinstellingen',
        'fr': 'Paramètres de Connexion Série',
        'it': 'Impostazioni Connessione Seriale',
        'es': 'Configuración de Conexión Serie',
        'pl': 'Ustawienia Połączenia Szeregowego',
        'uk': 'Налаштування Послідовного З\'єднання',
        'zh-cn': '串行连接设置'
    },
    'serial_path': {
        'en': 'Serial Port Path',
        'de': 'Serieller Port Pfad',
        'ru': 'Путь к последовательному порту',
        'pt': 'Caminho da Porta Serial',
        'nl': 'Seriële Poort Pad',
        'fr': 'Chemin du Port Série',
        'it': 'Percorso Porta Seriale',
        'es': 'Ruta del Puerto Serie',
        'pl': 'Ścieżka Portu Szeregowego',
        'uk': 'Шлях до Послідовного Порту',
        'zh-cn': '串口路径'
    },
    'baud_rate': {
        'en': 'Baud Rate',
        'de': 'Baudrate',
        'ru': 'Скорость передачи',
        'pt': 'Taxa de Transmissão',
        'nl': 'Baudrate',
        'fr': 'Débit en Bauds',
        'it': 'Velocità di Trasmissione',
        'es': 'Velocidad de Transmisión',
        'pl': 'Szybkość Transmisji',
        'uk': 'Швидкість Передачі',
        'zh-cn': '波特率'
    },
    'open_delay': {
        'en': 'Open Delay (ms)',
        'de': 'Öffnungsverzögerung (ms)',
        'ru': 'Задержка открытия (мс)',
        'pt': 'Atraso de Abertura (ms)',
        'nl': 'Open Vertraging (ms)',
        'fr': 'Délai d\'Ouverture (ms)',
        'it': 'Ritardo di Apertura (ms)',
        'es': 'Retraso de Apertura (ms)',
        'pl': 'Opóźnienie Otwarcia (ms)',
        'uk': 'Затримка Відкриття (мс)',
        'zh-cn': '打开延迟 (毫秒)'
    },
    'reconnect_interval': {
        'en': 'Reconnect Interval (ms)',
        'de': 'Wiederverbindungsintervall (ms)',
        'ru': 'Интервал переподключения (мс)',
        'pt': 'Intervalo de Reconexão (ms)',
        'nl': 'Herverbindingsinterval (ms)',
        'fr': 'Intervalle de Reconnexion (ms)',
        'it': 'Intervallo di Riconnessione (ms)',
        'es': 'Intervalo de Reconexión (ms)',
        'pl': 'Interwał Ponownego Połączenia (ms)',
        'uk': 'Інтервал Перепідключення (мс)',
        'zh-cn': '重连间隔 (毫秒)'
    },
    'rollershutters_configuration': {
        'en': 'Rollershutters Configuration',
        'de': 'Rollläden Konfiguration',
        'ru': 'Конфигурация рольставен',
        'pt': 'Configuração de Persianas',
        'nl': 'Rolluiken Configuratie',
        'fr': 'Configuration des Volets Roulants',
        'it': 'Configurazione Tapparelle',
        'es': 'Configuración de Persianas',
        'pl': 'Konfiguracja Rolet',
        'uk': 'Конфігурація Ролет',
        'zh-cn': '卷帘配置'
    },
    'add_rollershutter': {
        'en': 'Add Rollershutter',
        'de': 'Rollladen hinzufügen',
        'ru': 'Добавить рольставню',
        'pt': 'Adicionar Persiana',
        'nl': 'Rolluik Toevoegen',
        'fr': 'Ajouter Volet Roulant',
        'it': 'Aggiungi Tapparella',
        'es': 'Añadir Persiana',
        'pl': 'Dodaj Roletę',
        'uk': 'Додати Ролету',
        'zh-cn': '添加卷帘'
    },
    'name': {
        'en': 'Name',
        'de': 'Name',
        'ru': 'Имя',
        'pt': 'Nome',
        'nl': 'Naam',
        'fr': 'Nom',
        'it': 'Nome',
        'es': 'Nombre',
        'pl': 'Nazwa',
        'uk': 'Ім\'я',
        'zh-cn': '名称'
    },
    'id': {
        'en': 'ID',
        'de': 'ID',
        'ru': 'ID',
        'pt': 'ID',
        'nl': 'ID',
        'fr': 'ID',
        'it': 'ID',
        'es': 'ID',
        'pl': 'ID',
        'uk': 'ID',
        'zh-cn': 'ID'
    },
    'open_command': {
        'en': 'Open Command',
        'de': 'Öffnen Befehl',
        'ru': 'Команда открытия',
        'pt': 'Comando de Abertura',
        'nl': 'Open Commando',
        'fr': 'Commande d\'Ouverture',
        'it': 'Comando di Apertura',
        'es': 'Comando de Apertura',
        'pl': 'Komenda Otwierania',
        'uk': 'Команда Відкриття',
        'zh-cn': '打开命令'
    },
    'close_command': {
        'en': 'Close Command',
        'de': 'Schließen Befehl',
        'ru': 'Команда закрытия',
        'pt': 'Comando de Fechamento',
        'nl': 'Sluit Commando',
        'fr': 'Commande de Fermeture',
        'it': 'Comando di Chiusura',
        'es': 'Comando de Cierre',
        'pl': 'Komenda Zamykania',
        'uk': 'Команда Закриття',
        'zh-cn': '关闭命令'
    },
    'stop_command': {
        'en': 'Stop Command',
        'de': 'Stopp Befehl',
        'ru': 'Команда остановки',
        'pt': 'Comando de Parada',
        'nl': 'Stop Commando',
        'fr': 'Commande d\'Arrêt',
        'it': 'Comando di Stop',
        'es': 'Comando de Parada',
        'pl': 'Komenda Zatrzymania',
        'uk': 'Команда Зупинки',
        'zh-cn': '停止命令'
    },
    'actions': {
        'en': 'Actions',
        'de': 'Aktionen',
        'ru': 'Действия',
        'pt': 'Ações',
        'nl': 'Acties',
        'fr': 'Actions',
        'it': 'Azioni',
        'es': 'Acciones',
        'pl': 'Akcje',
        'uk': 'Дії',
        'zh-cn': '操作'
    }
};